// English, Korean, Japanese, Simplified Chinese. Shared by the static build and UI.
export const rows=[
["How Google uses information","Google의 정보 사용 방식","Googleによる情報の利用方法","Google如何使用信息"],
['All tools','전체 도구','すべてのツール','全部工具'],
['Convert a file. Keep creating.','파일 변환, 간단하게.','ファイル変換を、シンプルに。','文件转换，轻松完成。'],
['Choose your file format to get started.','변환할 파일 형식을 선택하세요.','変換するファイル形式を選んでください。','选择要转换的文件格式。'],
['Source format','원본 파일 형식','元のファイル形式','源文件格式'],
['Convert from {0}','{0} 파일 변환','{0} から変換','从 {0} 转换'],
['{0} to {1}','{0} → {1} 변환','{0} → {1} 変換','{0} 转 {1}'],
['Convert {0} files to {1} in your browser.','브라우저에서 {0} 파일을 {1} 형식으로 변환하세요.','ブラウザーで {0} ファイルを {1} に変換します。','在浏览器中将 {0} 文件转换为 {1}。'],
['More tools','편의 도구','便利なツール','实用工具'],
['Tools','도구','ツール','工具'],
['Open tool','도구 열기','ツールを開く','打开工具'],
['About','소개','概要','关于'],
['Contact','문의','お問い合わせ','联系'],
['Privacy','개인정보처리방침','プライバシー','隐私政策'],
['Main navigation','주 메뉴','メインナビゲーション','主导航'],
['Language','언어','言語','语言'],
['Processed on your device','기기에서 안전하게 처리','お使いの端末で処理','在设备上处理'],
['No uploads. No account needed.','파일 업로드 없이, 가입 없이.','アップロードも登録も不要。','无需上传，无需注册。'],
['How it works','사용 방법','使い方','使用方法'],
['Output and limitations','결과 및 유의사항','出力と注意点','输出与注意事项'],
['Related tools','관련 도구','関連ツール','相关工具'],
['Select your {0} files.','{0} 파일을 선택하세요.','{0} ファイルを選択します。','选择 {0} 文件。'],
['Review the options and convert.','옵션을 확인하고 변환하세요.','設定を確認して変換します。','检查选项并转换。'],
['Download your results.','결과 파일을 다운로드하세요.','結果をダウンロードします。','下载转换结果。'],
['Selected files are processed in your browser. Download the results before closing this page.','선택한 파일은 브라우저에서 처리됩니다. 페이지를 닫기 전에 결과를 다운로드하세요.','選択したファイルはブラウザー内で処理されます。ページを閉じる前に結果をダウンロードしてください。','所选文件在浏览器中处理。关闭页面前请下载结果。'],
['Up to 20 files · 50 MB each · 100 MB total. PDF inputs: up to 100 pages per file. Password-protected PDFs are not supported.','최대 20개 · 파일당 50 MB · 합계 100 MB. PDF는 파일당 최대 100페이지이며 암호로 보호된 PDF는 지원하지 않습니다.','最大20ファイル・各50 MB・合計100 MB。PDFは各100ページまで。パスワード付きPDFには対応していません。','最多20个文件，每个50 MB，合计100 MB。每个PDF最多100页，不支持加密PDF。'],
['Enable JavaScript to use this tool.','이 도구를 사용하려면 JavaScript를 켜주세요.','このツールを使うにはJavaScriptを有効にしてください。','请启用JavaScript以使用此工具。'],
['Merge PDF','PDF 합치기','PDF 結合','合并 PDF'],
['Combine PDF documents in your chosen order.','원하는 순서대로 PDF 문서를 하나로 합치세요.','PDF文書を指定した順序で結合します。','按指定顺序合并PDF文档。'],
['Arrange your PDFs, merge and download.','PDF 순서를 정한 뒤 합치고 다운로드하세요.','PDFの順序を決め、結合してダウンロードします。','排列PDF顺序，合并并下载。'],
['All pages are merged. Bookmarks and digital signatures are not preserved.','모든 페이지를 합칩니다. 책갈피와 디지털 서명은 유지되지 않습니다.','全ページを結合します。ブックマークと電子署名は保持されません。','合并所有页面，不保留书签和数字签名。'],
['QR Code Generator','QR 코드 만들기','QRコード作成','生成二维码'],
['Create a QR code from text or a link.','문자나 링크로 QR 코드를 만드세요.','文字やリンクからQRコードを作成します。','将文字或链接生成二维码。'],
['Enter text, create a QR code and download the PNG.','내용을 입력하고 QR 코드를 만든 뒤 PNG로 다운로드하세요.','内容を入力してQRコードを作成し、PNGをダウンロードします。','输入内容，生成二维码并下载PNG。'],
['Up to 1,000 UTF-8 bytes. Test the downloaded QR code before printing.','최대 UTF-8 1,000바이트. 인쇄 전에 다운로드한 QR 코드를 스캔해 확인하세요.','UTF-8で最大1,000バイト。印刷前にダウンロードしたQRコードを確認してください。','最多1,000个UTF-8字节。打印前请测试下载的二维码。'],
['QR Code Reader','QR 코드 읽기','QRコード読取','识别二维码'],
['Read a QR code from an image.','이미지 속 QR 코드의 내용을 읽으세요.','画像内のQRコードを読み取ります。','读取图片中的二维码。'],
['Choose a QR image and copy its contents.','QR 이미지를 선택하고 인식된 내용을 복사하세요.','QR画像を選択し、読み取った内容をコピーします。','选择二维码图片并复制识别内容。'],
['PNG, JPG or WEBP up to 10 MB. One QR per image; extracted links are not opened automatically.','10 MB 이하 PNG·JPG·WEBP. 이미지당 QR 하나를 인식하며 추출된 링크는 자동으로 열리지 않습니다.','10 MB以下のPNG・JPG・WEBP。画像1枚につきQR1つ。リンクは自動では開きません。','支持10 MB以内的PNG、JPG、WEBP。每张图片一个二维码，不会自动打开识别出的链接。'],
['Image Resizer','이미지 크기 변경','画像サイズ変更','调整图片尺寸'],
['Set image width and height in pixels.','이미지의 가로·세로 픽셀 크기를 바꾸세요.','画像の幅と高さをピクセル単位で変更します。','以像素为单位调整图片宽度和高度。'],
['Select an image, set dimensions and download the PNG.','이미지와 크기를 선택한 뒤 PNG로 다운로드하세요.','画像を選び、サイズを指定してPNGをダウンロードします。','选择图片，设置尺寸并下载PNG。'],
['Keep aspect ratio enabled to avoid stretching. Enlarging an image does not recover lost detail.','이미지가 늘어나지 않도록 비율 유지를 켜세요. 이미지를 확대해도 손실된 세부 정보는 복원되지 않습니다.','変形を防ぐには縦横比を維持してください。拡大しても失われた細部は復元されません。','开启保持宽高比以避免拉伸。放大图片无法恢复丢失的细节。'],
['About Paper Switch','Paper Switch 소개','Paper Switch について','关于 Paper Switch'],
['Simple tools for everyday files.','일상 속 파일 작업을 간편하게.','日々のファイル作業を手軽に。','让日常文件处理更简单。'],
['Convert documents and images, merge PDFs, create and read QR codes, and resize images. Each tool runs in your browser.','문서·이미지 변환, PDF 합치기, QR 코드 생성·읽기, 이미지 크기 변경을 제공합니다. 각 도구는 브라우저에서 실행됩니다.','文書・画像変換、PDF結合、QRコード作成・読取、画像サイズ変更を提供します。各ツールはブラウザー内で動作します。','提供文档和图片转换、PDF合并、二维码生成与识别及图片尺寸调整。所有工具均在浏览器中运行。'],
['Questions or feedback?','질문이나 의견이 있으신가요?','ご質問やご意見はありますか？','有问题或建议？'],
['Email','이메일','メール','电子邮件'],
['Include the tool name, browser and error message. Please do not send confidential files.','도구 이름, 브라우저, 오류 메시지를 함께 알려주세요. 기밀 파일은 보내지 마세요.','ツール名、ブラウザー、エラーメッセージをお知らせください。機密ファイルは送らないでください。','请提供工具名称、浏览器和错误信息。请勿发送机密文件。'],
['How files and preferences are handled.','파일과 설정을 처리하는 방법을 안내합니다.','ファイルと設定の取り扱いについて。','了解文件和偏好设置的处理方式。'],
['Files and preferences','파일 및 설정','ファイルと設定','文件与偏好设置'],
['Selected files and QR contents are not uploaded to a conversion server. Your language preference is saved in this browser and can be removed by clearing site data.','선택한 파일과 QR 내용은 변환 서버에 업로드되지 않습니다. 언어 설정은 이 브라우저에 저장되며 사이트 데이터를 삭제하면 지울 수 있습니다.','選択したファイルやQRの内容は変換サーバーに送信されません。言語設定はこのブラウザーに保存され、サイトデータを消去すると削除できます。','所选文件和二维码内容不会上传至转换服务器。语言偏好保存在此浏览器中，可通过清除站点数据删除。'],
['Hosting and advertising','호스팅 및 광고','ホスティングと広告','托管与广告'],
["Cloudflare hosts this website. Google and its partners may use cookies and process information such as IP addresses, browser details and ad interactions to deliver and measure ads, depending on your settings and applicable consent choices.","Cloudflare가 이 웹사이트를 호스팅합니다. Google과 파트너는 설정 및 해당되는 동의 선택에 따라 쿠키를 사용하고 IP 주소, 브라우저 정보, 광고 상호작용 등의 정보를 처리하여 광고를 제공하고 성과를 측정할 수 있습니다.","このサイトはCloudflareがホストしています。Googleとそのパートナーは、設定や該当する同意内容に応じてCookieを使用し、IPアドレス、ブラウザー情報、広告操作などの情報を処理して広告の配信と測定を行う場合があります。","本网站由Cloudflare托管。根据您的设置及适用的同意选择，Google及其合作伙伴可能使用Cookie并处理IP地址、浏览器信息和广告互动等数据，以投放广告并衡量效果。"],
['For privacy questions, use the contact page. Emails are handled separately by the email provider.','개인정보 관련 질문은 문의 페이지를 이용해 주세요. 이메일은 이메일 제공업체가 별도로 처리합니다.','プライバシーに関するご質問はお問い合わせページをご利用ください。メールはメールサービス側で別途処理されます。','隐私相关问题请使用联系页面。邮件由邮件服务商单独处理。'],
['Page not found','페이지를 찾을 수 없습니다','ページが見つかりません','未找到页面'],
['Choose a tool from the home page.','홈에서 필요한 도구를 선택하세요.','ホームからツールを選んでください。','请从首页选择工具。'],
['Raster output uses a white background and cannot preserve selectable text or editable vectors. Choose a resolution suited to your needs.','이미지 결과는 흰 배경이며 선택 가능한 글자와 편집 가능한 벡터를 유지하지 않습니다. 용도에 맞는 해상도를 선택하세요.','画像出力は白背景で、選択可能な文字や編集可能なベクターは保持しません。用途に合う解像度を選んでください。','图片输出使用白色背景，不保留可选文字或可编辑矢量。请选择合适的分辨率。'],
['Vector shapes are retained where supported. Text may become outlines; scanned pages remain images.','지원되는 벡터 도형은 유지됩니다. 글자는 윤곽선으로 바뀔 수 있으며 스캔 페이지는 이미지로 남습니다.','対応するベクター形状を保持します。文字がアウトラインになる場合があります。スキャンページは画像のままです。','尽可能保留矢量图形。文字可能转为轮廓，扫描页面仍为图片。'],
['Text is saved as UTF-8. Pages without text use OCR in the selected language. Check recognition errors; original layout is not retained.','텍스트는 UTF-8로 저장됩니다. 글자가 없는 페이지는 선택한 언어로 OCR 처리합니다. 오인식 여부를 확인하세요. 원본 배치는 유지되지 않습니다.','文字をUTF-8で保存します。文字のないページは選択言語でOCR処理します。認識結果を確認してください。元のレイアウトは保持しません。','文字保存为UTF-8。无文字页面使用所选语言进行OCR。请检查识别错误，不保留原始排版。'],
['Images are embedded in SVG; this does not trace outlines or create editable vector shapes.','이미지를 SVG 안에 포함합니다. 윤곽선을 추적하거나 편집 가능한 벡터로 바꾸는 기능은 아닙니다.','画像をSVG内に埋め込みます。輪郭のトレースや編集可能なベクターへの変換は行いません。','将图片嵌入SVG，不会描摹轮廓或生成可编辑矢量图形。'],
['External SVG images and scripts are rejected. Complex filters and unavailable fonts may render differently.','SVG의 외부 이미지와 스크립트는 허용하지 않습니다. 복잡한 필터나 없는 글꼴은 다르게 표시될 수 있습니다.','SVGの外部画像やスクリプトは拒否されます。複雑なフィルターや未インストールのフォントは表示が異なる場合があります。','不允许SVG中的外部图片和脚本。复杂滤镜或缺失字体可能显示不同。'],
['Choose separate PDFs or combine files in list order. Transparency becomes white. Image text is not converted to editable text.','파일별 PDF 또는 목록 순서로 합친 PDF를 선택하세요. 투명 영역은 흰색이 되며 이미지의 글자는 편집 가능한 글자로 바뀌지 않습니다.','個別のPDFか一覧順に結合したPDFを選べます。透明部分は白になり、画像内の文字は編集可能な文字に変換されません。','可生成独立PDF或按列表顺序合并。透明区域变为白色，图片文字不会转为可编辑文字。'],
['Keep original pixel dimensions. Transparency becomes white, and animated WEBP uses its first frame. Re-encoding cannot recover lost detail.','원본 픽셀 크기를 유지합니다. 투명 영역은 흰색으로, 움직이는 WEBP는 첫 프레임으로 저장됩니다. 다시 저장해도 손실된 정보는 복원되지 않습니다.','元のピクセル寸法を維持します。透明部分は白になり、アニメーションWEBPは最初のフレームを使用します。失われた細部は復元されません。','保持原始像素尺寸。透明区域变为白色，动态WEBP仅使用第一帧。重新编码无法恢复丢失的细节。'],
['TIFF pages are processed individually. Uncompressed TIFF output can be large.','TIFF는 페이지별로 처리합니다. 압축하지 않은 TIFF 결과는 파일이 클 수 있습니다.','TIFFはページごとに処理します。非圧縮TIFFの出力は大きくなる場合があります。','TIFF按页处理。未压缩的TIFF输出可能较大。'],
['UTF-8 text is wrapped on A4 pages. Up to 200,000 characters and 100 pages. Tables and images are not reconstructed.','UTF-8 텍���트를 A4에 자동 줄바꿈합니다. 최대 20만 글자·100페이지이며 표와 이미지는 재구성하지 않습니다.','UTF-8テキストをA4に折り返します。最大20万文字・100ページ。表や画像は再構成しません。','将UTF-8文字自动换行排入A4页面。最多20万字、100页，不重建表格和图片。'],
['{0} | Paper Switch','{0} | Paper Switch','{0} | Paper Switch','{0} | Paper Switch']
];

rows.push(['Open-source notices','오픈소스 고지','オープンソース表記','开源声明']);
