import {initLanguages,setText,translate} from './i18n.js';
const $=id=>document.getElementById('gif-'+id);let frames=[],output,worker,timeout,dragged;
const language=()=>document.documentElement.lang;
const say=s=>setText($('status'),s);
function clearOutput(){if(output)URL.revokeObjectURL(output);output=null;$('download').hidden=true;$('replay').hidden=true;$('download').removeAttribute('href');$('preview').replaceChildren();const p=document.createElement('p');setText(p,'Add at least two images to begin.');$('preview').append(p);setText($('stats'),'');}
function draw(){ $('frames').replaceChildren();frames.forEach((frame,i)=>{const li=document.createElement('li');li.draggable=true;li.ondragstart=e=>{if($('editor').disabled){e.preventDefault();return;}dragged=i;};li.ondragover=e=>e.preventDefault();li.ondrop=e=>{e.preventDefault();if($('editor').disabled)return;if(Number.isInteger(dragged)){const [f]=frames.splice(dragged,1);frames.splice(i,0,f);dragged=null;clearOutput();draw();}};li.ondragend=()=>{dragged=null;};const img=document.createElement('img');img.src=frame.url;img.alt='';const name=document.createElement('span');name.textContent=(i+1)+'. '+frame.file.name;name.setAttribute('translate','no');li.append(img,name);[['↑','Move earlier',-1],['↓','Move later',1],['×','Remove image',0]].forEach(([symbol,label,delta])=>{const b=document.createElement('button');b.type='button';b.textContent=symbol;b.setAttribute('aria-label',translate(label,language()));b.disabled=delta===-1&&i===0||delta===1&&i===frames.length-1;b.onclick=()=>{clearOutput();say('');if(delta){[frames[i],frames[i+delta]]=[frames[i+delta],frames[i]];}else{URL.revokeObjectURL(frame.url);frames.splice(i,1);}draw();};li.append(b);});$('frames').append(li);});$('run').disabled=frames.length<2;}
function finish(){clearTimeout(timeout);worker?.terminate();worker=null;$('editor').disabled=false;$('cancel').hidden=true;}
$('files').onchange=async()=>{const files=[...$('files').files];$('files').value='';if(!files.length)return;clearOutput();if(frames.length+files.length>20||[...frames.map(f=>f.file),...files].reduce((s,f)=>s+f.size,0)>50*1048576||files.some(f=>!f.size||f.size>10*1048576||! /\.(jpe?g|png|webp)$/i.test(f.name))){say('Choose 2–20 JPG, PNG or WEBP images within the size limits.');return;}
 $('editor').disabled=true;say('Loading images…');const added=[];try{for(const file of files){const image=await createImageBitmap(file);try{if(image.width*image.height>24000000)throw Error();const c=document.createElement('canvas');const scale=Math.min(1,100/Math.max(image.width,image.height));c.width=Math.max(1,Math.round(image.width*scale));c.height=Math.max(1,Math.round(image.height*scale));c.getContext('2d').drawImage(image,0,0,c.width,c.height);const blob=await new Promise(resolve=>c.toBlob(resolve));if(!blob)throw Error();added.push({file,url:URL.createObjectURL(blob)});}finally{image.close();}}frames.push(...added);say('');draw();}catch{added.forEach(f=>URL.revokeObjectURL(f.url));say('Could not read this image.');}finally{$('editor').disabled=false;}};
for(const id of ['delay','size','repeat'])$(id).oninput=()=>{clearOutput();say('');};
$('run').onclick=()=>{clearOutput();const delay=Number($('delay').value);if(!Number.isFinite(delay)||delay<100||delay>2000){say('Use a frame duration from 100 to 2,000 ms.');return;}if(frames.length<2)return;$('editor').disabled=true;$('cancel').hidden=false;say('Creating GIF: 0/'+frames.length);try{worker=new Worker('/assets/gif-worker.js',{type:'module'});const fail=()=>{finish();say('Could not create the GIF. Try fewer or smaller images.');};worker.onerror=fail;timeout=setTimeout(fail,120000);worker.onmessage=({data})=>{if(data.error){fail();return;}if(data.progress){say('Creating GIF: '+data.progress+'/'+data.total);return;}const blob=new Blob([data.bytes],{type:'image/gif'});output=URL.createObjectURL(blob);const img=document.createElement('img');img.src=output;img.alt=translate('GIF preview',language());$('preview').replaceChildren(img);$('download').href=output;$('download').hidden=false;$('replay').hidden=false;setText($('stats'),'Ready: '+data.width+' × '+data.height+' px · '+(blob.size/1024).toFixed(1)+' KB');say('');finish();};worker.postMessage({files:frames.map(f=>f.file),delay:Math.round(delay/10)*10,size:Number($('size').value),repeat:$('repeat').checked});}catch{finish();say('Could not create the GIF. Try fewer or smaller images.');}};
$('cancel').onclick=()=>{finish();say('Creation cancelled.');};$('replay').onclick=()=>{const img=$('preview').querySelector('img');if(img){const src=img.src;img.removeAttribute('src');requestAnimationFrame(()=>{img.src=src;});}};
window.addEventListener('pagehide',()=>{finish();frames.forEach(f=>URL.revokeObjectURL(f.url));if(output)URL.revokeObjectURL(output);});document.addEventListener('paper-language-change',draw);initLanguages();
