import {initLanguages,setText,translate} from './i18n.js';import {createPrintDocument} from './html-document.js';
const $=id=>document.getElementById('html-'+id);let revision=0;
const status=s=>setText($('status'),s);
function invalidate(){revision++;$('print').disabled=true;status('The content changed. Update the preview before saving.');}
$('code').oninput=invalidate;for(const id of ['size','orientation','margin'])$(id).onchange=invalidate;
$('file').onchange=async()=>{invalidate();const token=revision,file=$('file').files[0];$('file').value='';if(!file)return;if(!/\.html?$/i.test(file.name)||!file.size||file.size>2*1024*1024){status('Use a non-empty UTF-8 HTML file or code up to 2 MB.');return;}try{const source=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());if(token!==revision)return;$('code').value=source;update();}catch{if(token===revision)status('Could not open this HTML file. Save it as UTF-8 and try again.');}};
function update(){const token=++revision;$('print').disabled=true;try{const doc=createPrintDocument($('code').value,{size:$('size').value,orientation:$('orientation').value,margin:$('margin').value});const frame=$('frame');frame.onload=()=>{if(token!==revision)return;$('print').disabled=false;status('Preview is ready. You can now save as PDF.');};frame.srcdoc=doc;}catch{status('Use a non-empty UTF-8 HTML file or code up to 2 MB.');}}
$('update').onclick=update;
$('example').onclick=()=>{const lang=document.documentElement.lang;const names={'ko':['월간 보고서','항목','내용','진행 현황','계획대로 진행 중'],ja:['月次レポート','項目','内容','進捗状況','予定どおり進行中'],'zh-CN':['月度报告','项目','内容','进展','按计划进行']};const a=names[lang]||['Monthly report','Item','Details','Progress','On schedule'];$('code').value='<style>body{color:#203a2d}h1{border-bottom:3px solid #28684f;padding-bottom:12px}table{width:100%}th,td{border:1px solid #ccd8cf;text-align:left;padding:12px}th{background:#edf5ef}</style><h1>'+a[0]+'</h1><table><tr><th>'+a[1]+'</th><th>'+a[2]+'</th></tr><tr><td>'+a[3]+'</td><td>'+a[4]+'</td></tr></table>';update();};
$('print').onclick=()=>{if($('print').disabled)return;try{$('frame').contentWindow.focus();$('frame').contentWindow.print();}catch{status('Your browser could not open printing. Try this page in Chrome, Edge or Safari with PDF printing available.');}};
initLanguages();$('code').placeholder=translate('Paste your HTML here.',document.documentElement.lang);document.addEventListener('paper-language-change',()=>{$('code').placeholder=translate('Paste your HTML here.',document.documentElement.lang);$('frame').title=translate('Document preview',document.documentElement.lang);});
